### ISSUE TITLE
[BUG] PackSample fails to build with Visual Studio 2019 v16.3

### ISSUE THREAD

**Issue by barnson** [microsoft/msix-packaging#224]
**Project**
MSIX SDK

**Describe the bug**
PackSample fails to build with Visual Studio 2019 v16.3.

**To Reproduce**
`makewin.cmd x86 --pack`

**Expected behavior**
Successful build.

**Screenshots**
Not quite a screen shot but:

    Scanning dependencies of target PackSample
    [ 98%] Building CXX object sample/PackSample/CMakeFiles/PackSample.dir/PackSample.cpp.obj
    PackSample.cpp
    Z:\VS\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\experimental/filesystem(26): fatal error C1189: #error:  The <experimental/filesystem> header providing std::experimental::filesystem is deprecated by Microsoft and will be REMOVED. It is superseded by the C++17 <filesystem> header providing std::filesystem. You can define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING to acknowledge that you have received this warning.
    NMAKE : fatal error U1077: 'Z:\VS\2019\Enterprise\VC\Tools\MSVC\14.23.28105\bin\Hostx86\x86\cl.exe' : return code '0x2'
    Stop.

**Platform**
x86

**Additional context**
Pack must be enabled, of course.
